In [ ]:
import torch

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
torch.cuda.is_available()

False

In [ ]:
one_d_array=torch.tensor([1.2,30.2,5.5])
one_d_array

tensor([ 1.2000, 30.2000,  5.5000])

In [ ]:
type(one_d_array)

torch.Tensor

In [ ]:
one_d_array.dtype

torch.float32

In [ ]:
one_d_array.shape

torch.Size([3])

In [ ]:
one_d_array.size()

torch.Size([3])

In [ ]:
two_d_array=torch.tensor([[1.2,30.2,5.5],[5,8,2]])
two_d_array

tensor([[ 1.2000, 30.2000,  5.5000],
        [ 5.0000,  8.0000,  2.0000]])

In [ ]:
two_d_array.size()

torch.Size([2, 3])

In [ ]:
two_d_array.shape

torch.Size([2, 3])

In [ ]:
two_d_array.ndim

2

In [ ]:
three_d_array=torch.tensor([[[1,2,5,3],[3,4,8,5]]])
three_d_array

tensor([[[1, 2, 5, 3],
         [3, 4, 8, 5]]])

In [ ]:
three_d_array.ndim

3

In [ ]:
three_d_array.shape

torch.Size([1, 2, 4])

In [ ]:
import torch

three_d_array = torch.tensor([
    [
        [1, 2, 5, 3],
        [3, 4, 8, 5],
        [64, 5, 4, 5]
    ],
    [
        [4, 5, 6, 6],
        [7, 8, 9, 10],
        [11, 12, 13, 14]
    ]
])

print(three_d_array.shape)  # Output: torch.Size([2, 3, 4])


torch.Size([2, 3, 4])


In [ ]:
three_d_array.shape

torch.Size([1, 3, 4])

In [ ]:
import torch

three_d_arrayq = torch.tensor([
    [

        [64, 5, 4, 5]
    ],
    [

        [11, 12, 13, 14]
    ]
])

print(three_d_arrayq.shape)  # Output: torch.Size([2, 3, 4])


torch.Size([2, 1, 4])
